version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: starting_container
    image: starting-club-backend:latest
    ports:
      - "8082:8082"

    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: starting_club
      MYSQL_ROOT_PASSWORD : anisanis
      MYSQL_PASSWORD: anisanis
    ports:
      - "3307:3306"
    container_name: mysql_container
    volumes:
      - db-data:/var/lib/mysql
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
