spring:
  datasource:
    url: jdbc:mysql://${DB_PROD_HOST}:${DB_PROD_PORT}/starting_club_db
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082

jwt:
  access_secret_key : ${jwt.access_secret_key}
  refresh_secret_key : ${jwt.refresh_secret_key}
  refresh_expiration : ${jwt.refresh_expiration}
  access_expiration : ${jwt.access_expiration}
