spring:
  datasource:
    url: jdbc:mysql://db:3306/starting_club
    username: root
    password: anisanis
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0
    locations: classpath:db/migration
  #      url: jdbc:mysql://localhost:3306/starting_club
  #      user: root
  #      password: anisanis

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohamedanis2506@gmail.com
    password: bder km pl heus eqiv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
#    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
#    org.springframework: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet: DEBUG
#    org.springframework.web.method.annotation: DEBUG
#    org.springframework.validation: TRACE
#    org.springframework.http.converter.json: DEBUG
#    org.hibernate: ERROR


server:
  port: 8082
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

